[project]
name = "prayerapp"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "kivy[base]>=2.3.0"
]

[tool.uv]
no-build-isolation = true
